In [46]:
import pandas as pd
from konlpy.tag import Twitter

twitter = Twitter()

In [47]:
print(twitter.morphs('단독입찰보다 복수입찰의 경우'))

['단독', '입찰', '보다', '복수', '입찰', '의', '경우']


In [3]:
print(twitter.nouns(u'유일하게 항공기 체계 종합 개발'))

['항공기', '체계', '종합', '개발']


In [4]:
print(twitter.phrases(u'날카로운 분석과 신뢰감 있는 진행으로'))

['날카로운 분석', '날카로운 분석과 신뢰감', '날카로운 분석과 신뢰감 있는 진행', '분석', '신뢰', '진행']


In [5]:
print(twitter.pos(u'이것도 되나욬 ㅋㅋㅋ'))

[('이', 'Determiner'), ('것', 'Noun'), ('도', 'Josa'), ('되나욬', 'Noun'), ('ㅋㅋㅋ', 'KoreanParticle')]


In [6]:
print(twitter.pos(u'이것도 되나욬ㅋㅋ', norm=True))

[('이', 'Determiner'), ('것', 'Noun'), ('도', 'Josa'), ('되나요', 'Verb'), ('ㅋㅋ', 'KoreanParticle')]


In [38]:
print(twitter.pos(u'이것도 되나욬ㅋㅋ', norm=True, stem=True))
print(twitter.pos(u'shewasaboy', norm=True, stem=True))

[('이', 'Determiner'), ('것', 'Noun'), ('도', 'Josa'), ('되다', 'Verb'), ('ㅋㅋ', 'KoreanParticle')]
[('shewasaboy', 'Alpha')]


In [34]:
print(twitter.analyze(u'아이런것도 다 해주나요?????'))


AttributeError: 'Okt' object has no attribute 'analyze'

In [9]:
import warnings
warnings.simplefilter("ignore")

import konlpy
konlpy.__version__

'0.5.1'

In [10]:
from konlpy.corpus import kolaw
kolaw.fileids()

['constitution.txt']

In [11]:
c = kolaw.open('constitution.txt').read()
print(c[:40])

대한민국헌법

유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로


In [12]:
from konlpy.corpus import kobill
kobill.fileids()

['1809890.txt',
 '1809891.txt',
 '1809892.txt',
 '1809893.txt',
 '1809894.txt',
 '1809895.txt',
 '1809896.txt',
 '1809897.txt',
 '1809898.txt',
 '1809899.txt']

In [13]:
d = kobill.open('1809890.txt').read()
print(d[:40])

지방공무원법 일부개정법률안

(정의화의원 대표발의 )

 의 안
 번 호


In [15]:
from konlpy.tag import *

hannanum = Hannanum()
kkma = Kkma()
komoran = Komoran()
# mecab = Mecab()
okt = Okt()

# 이 캘래스들은 다음과 같은 메서드를 공통적으로 제공한다.

In [17]:
# 명사 추출
# 문자열에서 명사만 출출하려면 noun 명령어를 사용한다.


print(hannanum.nouns(c[:40]))
print(kkma.nouns(c[:40]))
print(okt.nouns(c[:40]))

['대한민국헌법', '유구', '역사', '전통', '빛', '우리', '대한국민', '3·1운동']
['대한', '대한민국', '대한민국헌법', '민국', '헌법', '유구', '역사', '전통', '우리', '국민', '3', '1', '1운동', '운동']
['대한민국', '헌법', '유구', '역사', '전통', '우리', '국민', '운동']


In [22]:
# 형태소 추출
# 명사 뿐 아니라 모든 품사의 형태소를 알아내려면 morphs 라는 명령어를 사용한다.

print(hannanum.morphs(c[:40]))
print(kkma.morphs(c[:40]))
print(okt.morphs(c[:40]))

['대한민국헌법', '유구', '하', 'ㄴ', '역사', '와', '전통', '에', '빛', '나는', '우리', '대한국민', '은', '3·1운동', '으로']
['대한민국', '헌법', '유구', '하', 'ㄴ', '역사', '와', '전통', '에', '빛나', '는', '우리', '대하', 'ㄴ', '국민', '은', '3', '·', '1', '운동', '으로']
['대한민국', '헌법', '\n\n', '유구', '한', '역사', '와', '전통', '에', '빛나는', '우리', '대', '한', '국민', '은', '3', '·', '1', '운동', '으로']


In [23]:
"""
품사 부착
pos 명령을 사용하면 품사 부착을 한다.
한국어 품사 태그세트로는 "21세기 세종계획 품사 태그세트" 를 비롯하여 다양한 품사 태그세트가 있다. 
형태소 분석기마다 사용하는 품사 태그가 다르므로 각 형태소 분석기ㅔ 대한 문서를 참조한다.
"""

hann

'\n품사 부착\npos 명령을 사용하면 품사 부착을 한다.\n한국어 품사 태그세트로는 "21세기 세종계획 품사 태그세트" 를 비롯하여 다양한 품사 태그세트가 있다. 형태소 분석기마다 사용하는 품사 태그가 다르므로 각 형태소 분석기ㅔ 대한 문서를 참조한다.\n'

In [24]:
hannanum.pos(c[:40])

[('대한민국헌법', 'N'),
 ('유구', 'N'),
 ('하', 'X'),
 ('ㄴ', 'E'),
 ('역사', 'N'),
 ('와', 'J'),
 ('전통', 'N'),
 ('에', 'J'),
 ('빛', 'N'),
 ('나는', 'J'),
 ('우리', 'N'),
 ('대한국민', 'N'),
 ('은', 'J'),
 ('3·1운동', 'N'),
 ('으로', 'J')]

In [25]:
kkma.pos(c[:40])

[('대한민국', 'NNG'),
 ('헌법', 'NNG'),
 ('유구', 'NNG'),
 ('하', 'XSV'),
 ('ㄴ', 'ETD'),
 ('역사', 'NNG'),
 ('와', 'JC'),
 ('전통', 'NNG'),
 ('에', 'JKM'),
 ('빛나', 'VV'),
 ('는', 'ETD'),
 ('우리', 'NNM'),
 ('대하', 'VV'),
 ('ㄴ', 'ETD'),
 ('국민', 'NNG'),
 ('은', 'JX'),
 ('3', 'NR'),
 ('·', 'SP'),
 ('1', 'NR'),
 ('운동', 'NNG'),
 ('으로', 'JKM')]

In [26]:
# komoran은 빈줄이 있으면 에러가 남
komoran.pos("\n".join([s for s in c[:40].split("\n") if s]))

[('대한민국', 'NNP'),
 ('헌법', 'NNP'),
 ('유구', 'XR'),
 ('하', 'XSA'),
 ('ㄴ', 'ETM'),
 ('역사', 'NNG'),
 ('와', 'JC'),
 ('전통', 'NNG'),
 ('에', 'JKB'),
 ('빛나', 'VV'),
 ('는', 'ETM'),
 ('우리', 'NP'),
 ('대하', 'VV'),
 ('ㄴ', 'ETM'),
 ('국민', 'NNP'),
 ('은', 'JX'),
 ('3', 'SN'),
 ('·', 'SP'),
 ('1', 'SN'),
 ('운동', 'NNP'),
 ('으로', 'JKB')]

In [27]:
okt.pos(c[:40])

[('대한민국', 'Noun'),
 ('헌법', 'Noun'),
 ('\n\n', 'Foreign'),
 ('유구', 'Noun'),
 ('한', 'Josa'),
 ('역사', 'Noun'),
 ('와', 'Josa'),
 ('전통', 'Noun'),
 ('에', 'Josa'),
 ('빛나는', 'Verb'),
 ('우리', 'Noun'),
 ('대', 'Modifier'),
 ('한', 'Modifier'),
 ('국민', 'Noun'),
 ('은', 'Josa'),
 ('3', 'Number'),
 ('·', 'Punctuation'),
 ('1', 'Number'),
 ('운동', 'Noun'),
 ('으로', 'Josa')]

In [31]:
tagsets = pd.DataFrame()
N = 67
tagsets["Hannanum-기호"] = list(hannanum.tagset.keys()) + list("*" * (N - len(hannanum.tagset)))
tagsets["Hannanum-품사"] = list(hannanum.tagset.values()) + list("*" * (N - len(hannanum.tagset)))
tagsets["Kkma-기호"] = list(kkma.tagset.keys()) + list("*" * (N - len(kkma.tagset)))
tagsets["Kkma-품사"] = list(kkma.tagset.values()) + list("*" * (N - len(kkma.tagset)))
tagsets["Komoran-기호"] = list(komoran.tagset.keys()) + list("*" * (N - len(komoran.tagset)))
tagsets["Komoran-품사"] = list(komoran.tagset.values()) + list("*" * (N - len(komoran.tagset)))
tagsets["OKT-기호"] = list(okt.tagset.keys()) + list("*" * (N - len(okt.tagset)))
tagsets["OKT-품사"] = list(okt.tagset.values()) + list("*" * (N - len(okt.tagset)))
tagsets

Hannanum-기호 Hannanum-품사 Kkma-기호     Kkma-품사 Komoran-기호 Komoran-품사  \
0            E          어미      EC       연결 어미         EC      연결 어미   
1           EC       연결 어미     ECD   의존적 연결 어미         EF      종결 어미   
2           EF       종결 어미     ECE    대등 연결 어미         EP      선어말어미   
3           EP       선어말어미     ECS   보조적 연결 어미        ETM  관형형 전성 어미   
4           ET       전성 어미      EF       종결 어미        ETN  명사형 전성 어미   
..         ...         ...     ...         ...        ...        ...   
62           *           *     XPV      용언 접두사          *          *   
63           *           *      XR          어근          *          *   
64           *           *     XSA  형용사 파생 접미사          *          *   
65           *           *     XSN    명사파생 접미사          *          *   
66           *           *     XSV   동사 파생 접미사          *          *   

         OKT-기호 OKT-품사  
0     Adjective    형용사  
1        Adverb     부사  
2         Alpha    알파벳  
3   Conjunction    접속사  
4    Determiner    관형사  
..          ...    ...  
62            *      *  
63            *      *  
64            *      *  
65            *      *  
66            *      *  

[67 rows x 8 columns]

In [33]:
Kkma.pos('she was a boy')

TypeError: pos() missing 1 required positional argument: 'phrase'

1. 토큰화(Tokenization) : 문자열에서 단어로 분리시키는 단계
2. 불용어 제거 (Stop word elimination) : 전치사, 관사 등 너무 많이 등장하는 단어 등 문장이나 문서의 특징을 표현하는데 불필요한 단어를 삭제하는 단계
3. 어간 추출 (Stemming) : 단어의 기본 형태를 추출하는 단계
4. 문서 표현 (Representation) : 주어진 문서나 문장을 하나의 벡터로 표현하는 단계, 단어들을 모두 인덱싱(indexing)하고 주어진 문서에 존재하는 단어의 빈도수를 사용하여 문서를 표현

In [39]:
documents = [
    ['왕자', '가', '공주', '를', '좋아한다'],
    ['공주', '가', '왕자', '를', '좋아한다'],
    ['시녀', '가', '왕자', '를', '싫어한다'],
    ['공주', '가', '시녀', '를', '싫어한다'],
    ['시녀', '가', '왕자', '를', '독살한다'],
    ['시녀', '가', '공주', '를', '독살한다']
]
words = set(sum(documents, []))
print(words)

{'왕자', '공주', '좋아한다', '싫어한다', '시녀', '독살한다', '를', '가'}


In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [69]:
# 하나의 Counter Vector 를 만든다.
# 이 때 전달하는 인자 min_df는 해당 값보다 빈도수가 낮은 단어는 무시하겠다는 뜻
# max_df 인자는 해당 값보다 많이 나오는, 빈도수가 높은 단어는 무시하겠다라는 뜻


vectorizer = CountVectorizer(min_df=1)
content = ["아버지 가 가방 에 들어 가신다", "엄마 가 가방에 들어 갔다"]

# fit_transform 함수를 통해 Counter Vector로 만들 수 있다
X = vectorizer.fit_transform(content)
print(X)
# 출력

print(vectorizer.get_feature_names())
print(X.toarray())

  (0, 5)	1
  (0, 0)	1
  (0, 4)	1
  (0, 2)	1
  (1, 4)	1
  (1, 6)	1
  (1, 1)	1
  (1, 3)	1
['가방', '가방에', '가신다', '갔다', '들어', '아버지', '엄마']
[[1 0 1 0 1 1 0]
 [0 1 0 1 1 0 1]]


## 게시물 분류하기

#### 01) 카운트 벡터 만들기

짧은 글 5개를 이용하여 Count Vector의 거리르 계산해 보도록 하자
짧은 글은 아래와 같다.

 1. This is a toy post about machine learning. Actually, it contains not much interesting stuff.
 2. Imaging databases provide storage capabilities.
 3. Most imaging databases save images permanently.
 4. Imaging databases store data.
 5. Imaging databases store data. Imaging databases store data. Imaging databases store data.

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
import os
import numpy as np

# 파일 리스트를 불러와 파일을 읽어 list에 저장해준다.
# os.listdir 을 통해 해당 디렉토리 하위의 파일 경로를 모두 불러온 후
# os.path.join을 통해 디렉토리 경로를 합친 후 read() 로 읽어 list에 담습니다.

posts = [
    "This is a toy post about machine learning. Actually, it contains not much interesting stuff.",
    "Imaging databases provide storage capabilities.",
    "Most imaging databases save images permanently.",
    "Imaging databases store data.",
    "Imaging databases store data. Imaging databases store data. Imaging databases store data."
    
]

In [22]:
vectorizer = CountVectorizer(min_df=1, stop_words="english")

In [23]:
new_post = "imaging databases"
new_post_vec = vectorizer.transform([new_post])

# transform Vs fit_transform 
# transform  : 인자로 하나의 문자열을 받는다..
# fit_transform  : 인자로 list 형태의 문자열을 받는다


NotFittedError: CountVectorizer - Vocabulary wasn't fitted.

In [24]:
print(new_post_vec)

  (0, 0)	1
  (0, 1)	1


In [25]:
print(new_post_vec.toarray())


[[1 1]]


In [26]:
def dist_raw(v1, v2):
    delta = v1 - v2
    # norm(): 벡터 간에 유클리드 거리를 계산
    return np.linalg.norm(delta)

In [31]:
import sys
best_dist = sys.maxsize
best_doc = None
best_i = None
X_train = np.array([0])

for i, post in enumerate(posts):
    post_vec = X_train.toarray()[i]
    # 벡터 사이의 거리를 구하기 위해서는 1차원 배열을 이용해야 하기 때문에 [0], 인덱스를 지정합니다.
    d = dist_raw(post_vec, new_post_vec.toarray()[0])
    print("=== Post %i with dist = %.2f: %s" %(i, d, post))
    if d<best_dist:
        best_dist = d
        best_i = i

print("Best post is %i with dist=%.2f" % (best_i, best_dist))

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 단순하게 상속받는 클래스 이름만 바꿔주면 됩니다.
class StemmedCountVector(TfidfVectorizer) :

    def build_analyzer(self):
        analyzer = super(StemmedCountVector, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

vectorizer = StemmedCountVector(min_df=1, stop_words="english", decode_error='ignore')

In [35]:
from konlpy.tag import Okt
import re
okt = Okt()

In [43]:
token = re.sub("(\.)","","정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")
# 정규 표현식을 통해 온점을 제거하는 정제 작업.
print(token)

정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다


In [48]:
token = okt.morphs(token)
# OKT 혀태소 분석기를 통해 토큰화 작업을 수행한 뒤에, token에다가 넣는다

word2index= {}
bow = []

for voca in token :
    if voca not in word2index.keys() :
        word2index[voca] = len(word2index)
        
# token 을 읽으면서, word2index 에 없는 (not in ) 단어는 새로 추가하고 , 이미 있는 단어는 ㅓㄴㅁ긴다.
        bow.insert(len(word2index)-1,1)
# bow 전체에 전부 기본값 1을 넣어준다,  단어의 개수는 최소 1개 이상이기 떄문이다
    else :
        index=word2index.get(voca)
        #재등장하는 단어의 인덱스를 받아온다
        bow[index] = bow[index] + 1
        #재등장한 단어는 해당 인덱스의 위치에 1을 더한다
        
print(word2index)

{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}


In [49]:
bow

[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]

문서1에 각 단어에 대해서 인덱스를 부여한 결과는 첫번째 출력 결과입니다. 문서1의 BoW는 두번째 출력 결과입니다. 두번째 출력 결과를 보면, 물가상승률의 인덱스는 4이며, 문서1에서 물가상승률은 2번 언급되었기 때문에 인덱스 4(다섯번째 값)에 해당하는 값이 2임을 알 수 있습니다. 

- (원한다면 한국어에서 불용어에 해당되는 조사들 또한 제거하여 더 정제된 BoW를 만들 수도 있습니다.)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [52]:
# 사용자가 직접 정의한 불용어 사용

from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [53]:
# COuntVetorizer 에서 제공하는 자체 불용어 사용

from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [7]:
# NLTK 에서 지원하는 불용어 사용

from sklearn.feature_extraction.text import CountVectorizer
text=["Family is not an important thing. It's everything."]
from nltk.corpus import stopwords
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}
