# Simple NN 구현

In [79]:
import numpy as np 

In [41]:
applePie = np.array([1,0,0])
bugger = np.array([0,1,0])
chicken = np.array([0,0,1])

In [42]:
sunnyDay = np.array([1,0])
rainyDay = np.array([0,1])

화창한 SunnyDay 일떄는 ApplePie 를 ,
비가 오는날엔 Bugger를 먹는다.

In [43]:
matrix = np.array([[1,0],[0,1],[0,0]])

In [44]:
np.dot(matrix,sunnyDay.T)
# SunnyDay 니깐 ApplePie를 먹는다.

array([1, 0, 0])

# simple RNN 구현하기

In [124]:
food_matrix = np.array([[[1,0,0],[0,1,0],[0,0,1]],[[0,0,1],[1,0,0],[0,1,0]]])
weather_matrix = np.array([[[1,0],[1,0],[1,0]],[[0,1],[0,1],[0,1]]])

In [125]:
def makeonehot(c) :
    # [[0,1,0],[1,2,1]] 를 [[0,0,0],[0,1,0]] 과 같이 인코딩 하려면 어떻게 해야 할까..?
    
    for i in range(len(c)) :
        if(c[i] !=2) :
            c[i] = 0
        else :
            c[i] = 1
    return c




In [126]:
h_t = applePie
x_t = rainyDay

foodV = np.dot(food_matrix,h_t)
weatherV = np.dot(weather_matrix,x_t)
food_weather = np.concatenate((foodV+weatherV))
oneHot_food2weather = makeonehot(food_weather).reshape(2,3)

In [127]:
h_t = oneHot_food2weather[0]+oneHot_food2weather[1]

In [128]:
h_t

array([0, 1, 0])

In [135]:
x_t = np.array([[0,1],[1,0],[1,0],[0,1],[1,0],[0,1]]) # 흐림, 맑음, 맑음, 흐림, 맑음, 흐림
h_t = np.array([[1,0,0]])

def simpleRNN (x_t,h_t) :
    ht = h_t
    for i in range(len(x_t)) :
        foodV = np.dot(food_matrix,ht[i])
        weatherV = np.dot(weather_matrix,x_t[i])
        food_weather = np.concatenate((foodV+weatherV))
        oneHot_food2weather = makeonehot(food_weather).reshape(2,3)
        hap = oneHot_food2weather[0]+oneHot_food2weather[1]
        ht = np.append(ht,[hap], axis=0)
        
    return ht

print(simpleRNN(x_t,h_t))

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]]
